# Analysis of Musical Quality Metrics

This notebook loads the musical quality metrics from `musical_quality_metrics_xlstm_84000.csv` and computes summary statistics (mean ± standard deviation).

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the metrics CSV
csv_path = "musical_quality_metrics_xlstm_84000.csv"
df = pd.read_csv(csv_path)

print(f"Loaded {len(df)} rows from {csv_path}")
df.head()

Loaded 80 rows from musical_quality_metrics_xlstm_84000.csv

,file,bars_N,global_key,key_stability,key_change_rate,chord_diversity,pitch_range,stepwise_ratio,note_density_mean,note_density_std,duration_entropy,error
0,temp_0.6_bars_16_001.mid,29,C:maj,0.965517,0.035714,0.068966,1.0,1.000000,4.000000,0.000000,0.360231,NaN
1,temp_0.6_bars_16_002.mid,16,C:maj,0.500000,0.800000,0.312500,28.0,0.462121,22.625000,7.490619,1.277264,NaN
2,temp_0.6_bars_16_003.mid,20,C:maj,1.000000,0.000000,0.100000,10.0,0.811321,16.000000,0.000000,-0.000000,NaN
3,temp_0.6_bars_16_004.mid,19,G:maj,1.000000,0.000000,0.315789,35.0,0.900662,10.473684,3.330377,0.152297,NaN
4,temp_0.6_bars_16_005.mid,17,A:maj,0.882353,0.062500,0.117647,5.0,0.729282,14.470588,4.202487,0.820824,NaN

In [3]:
# Filter out rows with errors if any
if 'error' in df.columns:
    df_clean = df[df['error'].isna() | (df['error'] == "") | (df['error'].astype(str) == "nan")].copy()
    print(f"Rows after filtering errors: {len(df_clean)}")
else:
    df_clean = df.copy()
    
# Select numeric columns for aggregation
numeric_cols = [
    "bars_N",
    "key_stability", 
    "key_change_rate", 
    "chord_diversity", 
    "pitch_range", 
    "stepwise_ratio", 
    "note_density_mean", 
    "note_density_std", 
    "duration_entropy"
]

# Ensure they are numeric
for col in numeric_cols:
    if col in df_clean.columns:
        df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

Rows after filtering errors: 80

In [4]:
# Compute Mean and Std
summary_data = []

for col in numeric_cols:
    if col in df_clean.columns:
        mean_val = df_clean[col].mean()
        std_val = df_clean[col].std()
        
        summary_data.append({
            "Metric": col,
            "Mean": mean_val,
            "Std": std_val,
            "Formatted": f"{mean_val:.4f} ± {std_val:.4f}"
        })

summary_df = pd.DataFrame(summary_data)

# Display the summary table
pd.set_option('display.max_colwidth', None)
display(summary_df[['Metric', 'Formatted']])

              Metric          Formatted
0             bars_N  31.5875 ± 19.2398
1      key_stability    0.5211 ± 0.2855
2    key_change_rate    0.4797 ± 0.3058
3    chord_diversity    0.4283 ± 0.2168
4        pitch_range  38.0000 ± 19.5221
5     stepwise_ratio    0.5308 ± 0.2282
6  note_density_mean  31.7950 ± 18.3028
7   note_density_std   11.2843 ± 8.3111
8   duration_entropy    1.0289 ± 0.5807

In [5]:
# Optional: Save the summary to a CSV/Markdown if needed
summary_df.to_csv("metrics_summary_xlstm_84000.csv", index=False)
print(summary_df[['Metric', 'Formatted']].to_markdown(index=False))

| Metric            | Formatted         |
|:------------------|:------------------|
| bars_N            | 31.5875 ± 19.2398 |
| key_stability     | 0.5211 ± 0.2855   |
| key_change_rate   | 0.4797 ± 0.3058   |
| chord_diversity   | 0.4283 ± 0.2168   |
| pitch_range       | 38.0000 ± 19.5221 |
| stepwise_ratio    | 0.5308 ± 0.2282   |
| note_density_mean | 31.7950 ± 18.3028 |
| note_density_std  | 11.2843 ± 8.3111  |
| duration_entropy  | 1.0289 ± 0.5807   |